name: haffkamp
description: An application for customers to fix their campers.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-417.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  flick_video_player: ^0.5.0
  video_player: ^2.2.5
  flutter_native_splash: ^2.3.1
  url_launcher: ^6.0.10
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/videos/

flutter_native_splash:
  image: assets/images/splash.gif
  color: "#adce73"
  fill: true
